<?php
$lang['lang'] = 'th';
$lang['langs'] = 'ภาษาไทย';
$lang['hi'] = 'สวัสดี';
$lang['dashboard'] = 'หน้าหลัก';
$lang['welcome'] = 'ยินดีตอนรับ';
$lang['settings'] = 'ตั้งค่า';
$lang['website'] = 'เว็บไซต์';
$lang['profile'] = 'ข้อมูลส่วนบุคคล';
$lang['logout'] = 'ออกจากระบบ';
$lang['titleweb'] = 'ระบบบริหารจัดการเนื้อหา';
$lang['apps'] = 'Application';
$lang['site'] = 'เว็ปไซด์';
$lang['section'] = 'Section';
$lang['device'] = 'Device';
$lang['league'] = 'ลีก';
$lang['season'] = 'Season';
$lang['tournament'] = 'Tournament';
$lang['week'] = 'สัปดาห์';
$lang['kickoff'] = 'Kickoff';
$lang['trophy'] = 'รางวัล';
$lang['partner'] = 'Partner';
$lang['competition_results'] = 'ผลการแข่งขัน';
$lang['halftime'] = 'ครึ่งแรก';
$lang['team'] = 'ทีม';
$lang['number_of_team'] = 'จำนวนทีม';
$lang['number_of_match'] = 'จำนวนคู่ทั้งหมด';
$lang['number_of_member'] = 'จำนวนสมาชิกที่ทายผล';
$lang['result'] = 'การแข่งขัน';
$lang['teamhome'] = 'ทีมเจ้าบ้าน';
$lang['teamaway'] = 'ทีมเยือน';
$lang['favorite'] = 'ทีมต่อ';
$lang['doublie_point_flag'] = 'คะแนนคูณ 2';
$lang['predic'] = 'ผลการแข่งขันที่คาด';
$lang['preditor_game'] = 'ทำนายผลการแข่งขัน';
$lang['preditor_date'] = 'วันที่ทายผลการแข่งขัน';
$lang['between_date'] = 'ระหว่างวันที่';
$lang['announce'] = 'ประกาศผล';
$lang['top_of_the_week'] = 'จัดลำดับผู้ได้คะแนนสูงสุดประจำสัปดาห์';
$lang['view_match_of_week'] = 'คู่ที่ทายผลประจำสัปดาห์';
$lang['bonus_point'] = 'คะแนนพิเศษ';
$lang['calc'] = 'คำนวณคะแนนใหม่';
$lang['point'] = 'คะแนน';
$lang['score'] = 'คะแนน';
$lang['price'] = 'ราคา';
$lang['price2'] = 'ราคาเปลี่ยน';
$lang['num'] = 'น้ำ';
$lang['top_score'] = 'คะแนนสูงสุด';
$lang['isscore'] = 'คะแนนที่ได้';
$lang['calculate_success'] = 'คำนวณคะแนนใหม่เรียบร้อยแล้ว';
$lang['waiting'] = 'รอผลการแข่งขัน';
$lang['finish'] = 'การแข่งขันเสร็จสิ้น';
$lang['nouse'] = 'ไม่ใช้งาน';
$lang['use'] = 'ใช้งาน';
$lang['totalscore'] = 'คะแนนรวม';
$lang['reward_points'] = 'คะแนนสะสม';
$lang['deadline'] = 'หมดเวลาทายผล';
$lang['today'] = 'วันนี้';
$lang['men'] = 'คน';
$lang['register_member'] = 'จำนวนสมาชิกที่ลงทะเบียน';
$lang['play_game'] = 'เล่นเกมส์';
$lang['firstteam'] = '11 ผู้เล่นตัวจริง';
$lang['lineup'] = '11 ผู้เล่นตัวจริง';
$lang['location'] = 'สถานที่ตั้งสนาม';
$lang['vision'] = 'ทรรศนะ';
$lang['sort'] = 'จัดลำดับ';
$lang['country'] = 'ประเทศ';

$lang['company'] = 'Tded';
$lang['login'] = 'เข้าระบบ';
$lang['username'] = 'ผู้ใช้งาน';
$lang['fullname'] = 'ชื่อของผู้ใช้งานระบบ';
$lang['password'] = 'รหัสผ่าน';
$lang['remember'] = 'จำรหัสผ่าน';
$lang['forgot'] = 'ลืมรหัสผ่าน';
$lang['email'] = 'อีเมลล์';
$lang['sendemail'] = 'ส่งอีเมลล์';
$lang['register'] = 'ลงทะเบียน';
$lang['reset'] = 'ล้างข้อมูล';
$lang['petrieveassword'] = 'ลืมรหัสผ่าน';
$lang['enteryouremailandtoreceiveinstructions'] = 'ใส่อีเมลของคุณและเพื่อรับรหัสผ่าน';
$lang['repeatpassword'] = 'รหัสผ่านอีกครั้ง';
$lang['backtologin'] = 'กลับไปเข้าระบบ';
$lang['newuserregistration'] = 'ลงทะเบียนผู้ใช้ใหม่';
$lang['enteryourdetailstobegin'] = 'ใส่รายละเอียดของคุณ';
$lang['iaccept'] = 'ยอมรับ';
$lang['useragreement'] = 'ข้อตกลงการใช้งาน';
$lang['dark'] = 'มืด';
$lang['blur'] = 'เบลอ';
$lang['light'] = 'สว่าง';
$lang['allrightsreserved'] = 'สงวนลิขสิทธิ์.';
$lang['home'] = 'หน้าแรก';
$lang['admin'] = 'ผู้บริหารระบบบ';
$lang['back'] = 'ย้อนกลับ';
$lang['backto'] = 'ย้อนกลับไป';
$lang['togglesidebar'] = 'แถบเครื่องมือ';
$lang['upload'] = 'อับโหลดไฟล์';
$lang['upload_max_filesize'] = 'ขนาดไฟล์ที่สามารถอับโหลดได้';
$lang['ads'] = 'Ads';
$lang['type'] = 'ประเภท';
$lang['block'] = 'Block';
$lang['activity_logs'] = 'บันทึกการจัดการระบบ';
$lang['vdo'] = 'คลิป';
$lang['use'] = 'ใช้งาน';
$lang['auto_tags'] = 'ใส่ Tags อัตโนมัติ';
$lang['other_link'] = 'ลิงค์ ออกเว็บไซต์นอก';
$lang['import_csv'] = 'นำเข้า CSV ไฟล์';
$lang['upload_clip'] = 'Upload clip';
$lang['require'] = 'จำเป็น';
$lang['Elvis'] = 'Elvis';
$lang['of'] = 'ของ';
$lang['popular_vote'] = 'Popular vote';
$lang['page'] = 'page';

$lang['no_approve'] = 'ยังไม่ได้ทำการ Approve ';
$lang['generate_catch'] = 'สร้างแคชไฟล์';
$lang['sentmail_manager'] = 'Sent mail to manager';
$lang['waiting_for_generate'] = 'กำลังทำการ Generate file กรุณา รอจนกว่าจะทำงานเสร็จ';
$lang['please_contact_admin'] = 'กรุณาติดต่อแอดมินเพื่อทำการแก้ไข';
$lang['please_fillin'] = 'กรุณาใส่  ชื่อในวงการ ชื่อเล่น ชื่อ และ นามสกุลให้ครับด้วยครับ';
$lang['please_select_league'] = 'กรุณาใส่  league ด้วยครับ';
$lang['please_select_week'] = 'กรุณาใส่  week ด้วยครับ';
$lang['please_select_season'] = 'กรุณาใส่  season ด้วยครับ';

$lang['add'] = 'เพิ่ม';
$lang['update'] = 'แก้ไข';
$lang['edit'] = 'แก้ไข';
$lang['delete'] = 'ลบ';
$lang['status'] = 'สถานะ';
$lang['publish'] = 'แสดง';
$lang['unpublish'] = 'ไม่แสดง';
$lang['action'] = 'การกระทำ';
$lang['order_by'] = 'เรียงตาม';
$lang['register_date'] = 'วันที่ลงทะเบียน';
$lang['create_date'] = 'วันที่สร้าง';
$lang['create_by'] = 'สร้างโดย';
$lang['lastupdate'] = 'วันที่แก้ไข';
$lang['lastupdate_by'] = 'แก้ไขโดย';
$lang['search'] = 'ค้นหา';
$lang['success'] = 'สำเร็จ';
$lang['create'] = 'สร้าง';
$lang['bigsize'] = 'โลโก้ขนาดใหญ่';
$lang['approve'] = 'อนุมัติ';
$lang['activity'] = 'Activity';

$lang['start_date'] = 'วันเริ่มต้น';
$lang['end_date'] = 'วันสิ้นสุด';

$lang['access'] = 'การเข้าถึง';
$lang['access_menu'] = 'การเข้าถึงเมนู';
$lang['file_not_found'] = 'หาไม่เจอ.';
$lang['please_new_keyword'] = 'กรุณาใส่คำค้นหาใหม่.';
$lang['orientation'] = 'สลับแนวตัด';

$lang['vertical'] = 'แนวตั้ง';
$lang['horizontal'] = 'แนวนอน';
$lang['watermark'] = 'ลายน้ำ';
$lang['nowatermark'] = 'ไม่มีลายน้ำ';
$lang['topleft'] = 'บนซ้าย';
$lang['buttomright'] = 'ล่างขวา';

$lang['admin_menu'] = 'Admin menu';
$lang['homepage_menu'] = 'เว็บไซต์เมนู';
$lang['view'] = 'ดู';
$lang['credit'] = 'เครดิตภาพ';
$lang['columnist'] = 'คอลัมนิสต์';
$lang['submenu'] = 'เมนูย่อย';
$lang['order'] = 'เรียงลำดับ';
$lang['are you sure to add'] = 'คุณต้องการจะเพิ่มใช่ไหม ?';
$lang['are you sure to update'] = 'คุณต้องการจะแก้ไขใช่ไหม ?';
$lang['are you sure to delete'] = 'คุณต้องการจะลบใช่ไหม ?';
$lang['are you sure to restore'] = 'คุณต้องการจะนำกลับมาใช้ใช่ไหม ?';
$lang['are you sure to set default picture'] = 'คุณต้องการจะตั้งเป็นภาพหลักใช่ไหม?';
$lang['drag and drop'] = 'ลากและวาง';
$lang['admin_team'] = 'Admin Group';

$lang['list_tv'] = 'รายการทีวี';
$lang['sortby'] = 'เรียงตาม';
$lang['gender'] = 'เพศ';
$lang['admin logs activity'] = 'Logs activity';
$lang['upload_file'] = 'คลิกเพื่อ อับโหลดไฟล์';

/***************member***********************/
$lang['fullname'] = 'ชื่อเต็ม';
$lang['name'] = 'ชื่อ';
$lang['firstname'] = 'ชื่อ';
$lang['lastname'] = 'สกุล';
$lang['admin_level'] = 'ระดับผู้ใช้งาน';
$lang['add_member'] = 'เพิ่มสมาชิก';
$lang['edit_member'] = 'แก้ไขสมาชิก';
$lang['member_list'] = 'รายชื่อสมาชิก';
$lang['basic_info'] = 'ข้อมูลพื้นฐาน';
$lang['general'] = 'ทั่วไป';
$lang['contact'] = 'ติดต่อ';
$lang['social'] = 'สังคม ';
$lang['phone'] = 'โทรศัพท์ ';
$lang['mobile'] = 'มือถือ ';
$lang['new_password'] = 'รหัสผ่านใหม่';
$lang['confirm_password'] = 'ยืนยันรหัสผ่าน';

$lang['admin_type'] = 'ประเภทแอดมิน';
$lang['admin_type_title'] = 'ชื่อ ประเภท';
$lang['programtv'] = 'รายการทีวี';
$lang['channel'] = 'ช่องรายการ';
$lang['channel_id'] = 'ช่องรายการ';
$lang['channel_name'] = 'ชื่อช่องรายการ';
$lang['channel_icon'] = 'Channel icon';
$lang['channel_picture'] = 'ภาพใช้สำหรับ Shear Social';
$lang['datetime'] = 'วัน เวลา';
$lang['date'] = 'วัน';
$lang['time'] = 'เวลา';
$lang['center'] = 'กลาง';

/***************category***********************/
$lang['category'] = 'หมวดหมู่';
$lang['category_name'] = 'ชื่อหมวดหมู่';
$lang['add_category'] = 'เพิ่มหมวดหมู่';
$lang['type_of_column'] = 'ประเภทของบทความ';

/***************sub category***********************/
$lang['subcategory'] = 'หมวดหมู่ย่อย';
$lang['subcategory_name'] = 'ชื่อหมวดหมู่ย่อย';
$lang['add_subcategory'] = 'เพิ่มหมวดหมู่ย่อย';
$lang['sub_of'] = 'หมวดหมู่ย่อยของ';

/***************dara_type***********************/
$lang['dara_type'] = 'ประเภทของดารา';
$lang['dara_type_name'] = 'ชื่อประเภทของดารา';
$lang['dara'] = 'ดารา';
$lang['first_name'] = 'ชื่อ';
$lang['middle_name'] = 'ชื่อกลาง';
$lang['last_name'] = 'สกุล';
$lang['nickname'] = 'ชื่อเล่น';
$lang['pen_name'] = 'ชื่อในวงการ';
$lang['eng_name'] = 'English full name';

$lang['sex'] = 'เพศ';
$lang['male'] = 'ชาย';
$lang['female'] = 'หญิง';
$lang['birthday'] = 'วันเกิด';
$lang['address'] = 'ที่อยู่';
$lang['weight'] = 'น้ำหนัก';
$lang['height'] = 'ส่วนสูง';
$lang['education'] = 'การศึกษา';
$lang['hobby'] = 'งานอดิเรก';
$lang['picture'] = 'รูป';
$lang['profile'] = 'ข้อมูลส่วนตัว';
$lang['portfolio'] = 'ผลงาน';
$lang['lastportfolio'] = 'ผลงานล่าสุด';

$lang['grade1'] = 'มัธยมศึกษา';
$lang['grade2'] = 'ปริญญาตรี';
$lang['grade3'] = 'ปริญญาโท';
$lang['grade4'] = 'ปริญญาเอก';
$lang['filter'] = 'filter';
$lang['waiting for delete'] = 'รอลบ';
$lang['please drag on the image'] = 'กรุณาลากที่รูปภาพ';
$lang['picture'] = 'ภาพ';
$lang['crop image'] = 'Crop image';
$lang['can_comment'] = 'อนุญาตให้คอมเม้น';

/***************News***********************/
$lang['news'] = 'ข่าว';
$lang['send_select'] = 'ส่งข้อมูลที่เลือก';
$lang['please_select'] = 'กรุณาเลือก';
$lang['title'] = 'หัวข้อ';
$lang['caption'] = 'Caption';
$lang['shorttitle'] = 'โปรยข่าว';
$lang['display_date'] = 'วันที่ลง';
$lang['detail'] = 'รายละเอียด';
$lang['display_vdo'] = 'แสดงไอคอนวิดีโอ';

$lang['please_select_cat'] = 'กรุณาเลือก หมวดหมู่ข่าว และ หมวดหมู่ย่อย';
$lang['remark_date'] = 'Date Format YYY-MM-DD h:i:s (ค.ศ.) (ข้อควรระวัง หากใส่ ข้อมูลไม่ถูกต้อง จะไม่ถูกบันทึกข้อมูล)<br> หากต้องการกำหนดวันเริ่มต้น และ สิ้นสุดการดูข้อมูลให้ใส่';

/***************Tags***********************/
$lang['tags'] = 'Tags';
$lang['all'] = 'ทั้งหมด';

/***************Column***********************/
$lang['column'] = 'บทความ';
$lang['gallery'] = 'แกเลอรี่';
$lang['gallery_type'] = 'ประเภทแกเลอรี่';

$lang['rotate'] = 'หมุน';
$lang['left'] = 'วนไปทางซ้าย';
$lang['right'] = 'วนไปทางขวา';

$lang['full_name'] = 'ชื่อจริง';

$lang['add_edit_picture'] = 'เพิ่ม และ แก้ไขรูปภาพ';
$lang['preview'] = 'ดูตัวอย่าง';
$lang['set_default'] = 'ตั้งค่า หน้าปก';
$lang['default'] = 'หน้าปก';

$lang['relate'] = 'Relate';
$lang['search for tags news'] = 'ค้นหาข่าวสำหรับ Tags';
$lang['search for relate'] = 'ค้นหาสิ่งที่เกี่ยวข้อง';
$lang['search for tags dara'] = 'ค้นหาดารา สำหรับ Tags';
$lang['del relate'] = 'ลบ ข่าวที่เกี่ยวข้องทั้งหมด';

$lang['to'] = 'ถึง';
$lang['highlight'] = 'ไฮไลท์';
$lang['belong_to'] = 'สังกัด';
$lang['pin'] = 'ปักหมุด';
$lang['pin_date'] = 'วันที่ปักหมุด';
$lang['position'] = 'ตำแหน่งที่';
$lang['save'] = 'บันทึกข้อมูล';
$lang['save_order'] = 'บันทึกการจัดเรียงใหม่';
$lang['save_relate'] = 'บันทึกข่าวที่เกี่ยวข้อง';
$lang['zodiac'] = 'ราศี';
$lang['traffic_sources'] = 'แหล่งที่มา';

$lang['meta_description'] = 'Meta Description';
$lang['meta_description_seodoctor'] = '<p>Meta description tag&nbsp; is used for a brief description of the page. Although not a significant search engine ranking factor anymore, it is still used by all popular search engines when displaying search engine results. Having a good meta description can improve your chances of the visitor clicking on your result in the search engine.</p><p>Recommendations for meta descriptions include:</p><ul><li>Write a sensible description and avoid automated tools for generating meta description</li><li>You can include your popular keywords n the meta description as they will be bold when displayed in search engine results</li>	<li>Keep it up to around 70 words (350 characters). Search engines display variable length but they will pick the best bit to display based on user search</li></ul>';

$lang['import'] = 'นำเข้าสู่ระบบ';
$lang['match'] = 'แมตช์';
$lang['point'] = 'คะแนน';
$lang['update_score'] = 'Update score';
$lang['statistics'] = 'สถิติ';
$lang['bet'] = 'อัตราต่อรอง';
$lang['predict'] = 'คาดเดา';
$lang['review'] = 'วิจารณ์เกมการแข่งขัน';

$lang['player'] = 'ผู้เล่น';
$lang['list_player'] = 'รายชื่อนักเตะ';
$lang['last_match'] = 'ผลงานล่าสุด';
$lang['age'] = 'อายุ';
$lang['last_match_vs'] = 'ผลงานที่เจอกันล่าสุด';
$lang['lives'] = 'ถ่ายทอดสด';
$lang['logo_team'] = 'โลโก้ทีม';
$lang['referee'] = 'กรรมการ';
$lang['guru'] = 'เซียน';
$lang['tded'] = 'Tded เซียน';
$lang['stadium'] = 'สนามแข่ง';
$lang['formation'] = 'แผนการเล่น';
$lang['capacity'] = 'ความจุ';
$lang['manager'] = 'ผู้จัดการ';
$lang['color'] = 'สี';
$lang['short_name'] = 'ชื่อเรียก';
$lang['injured'] = 'injured';
$lang['position'] = 'position';
$lang['minutes'] = 'minutes';
$lang['appearences'] = 'appearences';
$lang['lineups'] = 'lineups';
$lang['substitute_in'] = 'substitute_in';
$lang['substitute_out'] = 'substitute_out';
$lang['substitutes_on_bench'] = 'substitutes_on_bench';
$lang['goals'] = 'goals';
$lang['assists'] = 'assists';
$lang['yellowcards'] = 'yellowcards';
$lang['yellowred'] = 'yellowred';
$lang['redcards'] = 'redcards';

$lang['import_statistics'] = 'นำสถิติเข้าสู่ระบบ';
$lang['import_match_to_system'] = 'วันที่นำเข้าระบบ';
$lang['get_commentaries'] = 'Get commentaries';
$lang['interesting'] = 'ข้อมูลที่น่าสนใจ';
$lang['update_result'] = 'อับเดตผลสกอร์';
$lang['trust'] = 'ความมั่นใจ';

$lang['fullmatch'] = 'จบการแข่งขัน';
$lang['postp'] = 'เลื่อนการแข่งขัน';
$lang['cancel'] = 'ยกเลิกการแข่งขัน';
?>